### ISSUE TITLE
Moderation commands.

### ISSUE THREAD

**Issue by Balthrox** [Comportment/Diax#4]
Kick \<user>
Ban \<user>
Nuke \<no. of messages>/<user><in last x messages>/<all Diax messages in last x messages>
Mute \<user><time>

**Comment by rainestormee** [comment]
Nuke?

**Comment by rainestormee** [comment]
`kick @mention` ?

**Comment by Balthrox** [comment]
Yup, Kick specific user.

**Comment by rainestormee** [comment]
https://github.com/Comportment/Diax/tree/master/src/main/java/io/bfnt/comportment/diax/commands/moderation
